### ISSUE TITLE
refresh 404.

### ISSUE THREAD

**Issue by leeduckgo** [WeLightProject/Tai-Shang-NFT-Wallet#7]
https://bewater.leeduckgo.com/contract-interactor, directly visit it will return 404.

**Comment by ankazen** [comment]
try this.
[https://www.coderrocketfuel.com/article/fix-404-error-when-using-react-rouder-dom-and-nginx](fix-404-error-when-using-react-rouder-dom-and-nginx)

**Comment by leeduckgo** [comment]
> try this. [https://www.coderrocketfuel.com/article/fix-404-error-when-using-react-rouder-dom-and-nginx](fix-404-error-when-using-react-rouder-dom-and-nginx)

thx a lot
